Вторая домашняя работа
Vladimir99users/UsefulStorageHomeWork pull request #2
Opened 2023-11-03 06:12 UTC by Vladimir99users

2023-11-03 08:45 UTC, Vladimir99users commented
![image](https://github.com/Vladimir99users/UsefulStorageHomeWork/assets/51012754/efaaa5fc-c094-4a39-bf38-a1ec8c24e5e5)

2023-11-04 01:44 UTC, progressicu requested changes

2023-11-04 01:44 UTC, progressicu commented on Storage/pom.xml
> +            <artifactId>mapstruct-processor</artifactId>
если не ошибаюсь, то это можно убрать из зависимостей и оставить только в annotationProcessorPaths

2023-11-04 01:44 UTC, progressicu commented on Storage/target/classes/TestFile.json
> +[
в репозиториях никогда не должно быть папки target, т.к. в ней всё скомпилированное лежит, что не нужно

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/Requests.java
>  public class Requests implements Requestable
Requests - как-то абстрактно и не связано с методами find... ниже 😅

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/RequestService.java
> +        objectMap = readData.readData(path);
бины не должны хранить состояние и которое изменяется. Это map-а должна была передаваться в конструктор/один раз инициализроваться в конструкторе

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/DisplayService.java
> +    public DisplayService(@NonNull RequestService service)
@RequiredArgsConstructor

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/DisplayService.java
> +
зачем тут два пропуска строки?

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/DisplayService.java
> +        if (Objects.isNull(obj))
ты через @NonNull проверил, что это поле не null, зачем снова проверяешь?

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/Main.java
> +    public CommandLineRunner run() {
Лучше сделать всё тоже самое, но как отдельный класс, который имплементирует данный интерфейс. В таком случае можно будет не через Autowired классы закидывать, а через конструктор и Main.java будет простой (как и должно быть)

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/RequestService.java
> +        objectMap = readData.readData(path);
Ну и этот класс отвечает только за работу с объектами. Чтение из файла - это точно что ему не нужно. Лучше это сделать в commandLineRunner, а сюда передать саму map и сделать putAll

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +   // @Value("${data.path}")
если что-то не нужно, то удаляем

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +        ObjectMapper mapper = new ObjectMapper();
Этот класс можно один раз создать, он по факту как бин, в себе не хранит состояние

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +        System.out.println(path);
я так понимаю это было для дебага - так что давай удалим это, зачем такое в продакш коде

2023-11-04 01:44 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +            nodes = mapper.readTree(file);
почитай про readValue и сделай через него. Это позволит значительно уменьшит код в этом методе

2023-11-04 01:44 UTC, progressicu commented on Storage/pom.xml
> +            <artifactId>jackson-databind</artifactId>
ты эту зависимость выше вроде объявил, зачем ещё раз

2023-11-04 01:44 UTC, progressicu commented on Storage/pom.xml
> +            <version>${org.jupiter.version}</version>
если не ошибаюсь, то все версии junit, mockito, lombok можно подтянуть из spring-boot-starter-parent

2023-11-06 03:06 UTC, Vladimir99users commented on Storage/pom.xml
> +            <version>${org.jupiter.version}</version>
оке доке

2023-11-06 03:36 UTC, Vladimir99users commented on Storage/src/main/java/org/example/DisplayService.java
> +        if (Objects.isNull(obj))
Затем, что nonNull рушит выполнение, а тут мы можем продолжать работать без проблем.

2023-11-06 04:02 UTC, Vladimir99users commented on Storage/src/main/java/org/example/Requests.java
>  public class Requests implements Requestable
ну Requests - запросы, как раз запрос на поиск по ID или по имени, в тот момент казалось, прям пушка бомба

2023-11-08 10:05 UTC, progressicu commented on Storage/pom.xml
> +            <artifactId>jackson-databind</artifactId>
не поправил

2023-11-08 10:27 UTC, progressicu requested changes

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/CommandLiner.java
> +    @Bean
зачем эта аннотация здесь? Можно на сам CommandLiner повесить @Component и всё
зря кстати выкинул runner из названия, как раз самая главная часть. Лучше переименовал бы

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/CommandLiner.java
> +    public void Initialize() throws IOException
1. camelCase
2. Зачем тут IOException
3. Зачем этот метод публичный и ты его откуда-то вызываешь. Ты кому-то другому (не контексту спринга) даешь заполнять этот бин. Тут либо а) использовать @PostConstruct б) лучший вариант. Переписать это 😁  

Переписать в том плане, что можно сделать так, что всякие сервисы создавались пустые и CommandLineRunner просто наполнял их в методе run (readable.readData(inputDataPath) + requestService.putAll) и в конце запускал displayService

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/Main.java
> +    public CommandLineRunner run() {
Давай скажу проще, выкини всё из Main класса. У тебя почти уже всё готово в CommandLiner, просто нужно правильно объявить это всё

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +    @Bean
Зачем эта аннотация здесь?

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +                long id =  Long.parseLong(String.format("%s%d", name.hashCode(), description.length()));
какая-то мутная схема. Пару вариантов: а) создавать UUID. Он можно сказать уникальный б) считать хэшкод от самого UsefulObject в) идентификатор сразу засунуть в json

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
>          }
сократи блок try. У тебя такая ошибка может быть только в readValue, а ты в блок сразу всё засовываешь

2023-11-08 10:27 UTC, progressicu commented on Storage/src/main/java/org/example/UsefulObject.java
> +@Data
Почитай про Data и какие аннотации она заменяет. Чтобы всё подряд не писать

2023-11-08 10:27 UTC, progressicu commented on Storage/src/test/java/org/example/RequestServiceTest.java
> +    @BeforeEach
1. Тебе не надо это делать перед каждым тестом
2. Это юнит тест RequestService, соответственно тебе не надо тут вычитывать данные из файла. Просто создай какой тебе нужно RequestService и проверяй его методы

2023-11-08 10:29 UTC, progressicu commented
- папка target через gitignore можно убрать, а не просто удалить
- Нужно больше тестов. Ты написал тесты только на один сервис, а у тебя ещё другие классы есть

2023-11-14 04:45 UTC, progressicu requested changes

2023-11-14 04:45 UTC, progressicu commented on Storage/.gitignore
> +cat ~/.gitignore
зачем это здесь?

2023-11-14 04:45 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +public class ReadDataFromFileTest
где AAA комменты?

2023-11-14 04:45 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +    public void unCorrectPathTest()
ты уверен, что в этом тесте ты проверяешь поведение ReadDataFromFile?

2023-11-14 04:45 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +    public void NotEmptyDataFromFile() throws IOException
camelCase

2023-11-14 04:45 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +        Readable reader = new ReadDataFromFile();
можно один раз на тестовый класс создать

2023-11-14 04:45 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +        Map<Long, UsefulObject> datas = reader.readData(file.getPath());
Если тебе нужен только file.getPath(), то почему не создать нужный объект, а не две строки и ещё файл

2023-11-14 04:45 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +        Assertions.assertFalse(datas.isEmpty());
Ты должен польностью проверить вплоть до содержания, этот класс же считывает UsefulObject, соответственно нужно проверить, что он правильно считал это всё

2023-11-14 04:49 UTC, progressicu commented on Storage/src/main/java/org/example/CommandLineRunner.java
> +    private void initializeComponent()
https://github.com/Vladimir99users/UsefulStorageHomeWork/pull/2#discussion_r1386380323 - перечитай в этом комменте ещё раз про создание всяких сервисов. Не

2023-11-14 04:50 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +            String name = usefulObject.getName();
и зачем ты вытащил name и description?

2023-11-17 04:48 UTC, progressicu commented on Storage/src/main/java/org/example/CommandLineRunner.java
> +        } catch (IOException exeption)
а кого ты тут отлавливаешь? У тебя же и так в readData есть этот перехват и там кидается ошибка

2023-11-17 04:48 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +            throw new RuntimeException("An error occurred while reading file: " + file.toString());
стоит внутрь новой RuntimeException положить и старое исключение IOException

2023-11-17 04:49 UTC, progressicu commented on Storage/src/main/java/org/example/ReadDataFromFile.java
> +    public List<UsefulObject> getListValue(String path)
1. почему этот метод public?
2. Между методами делай пропуск строки. Смотри за своим кодом, он должен быть красивым

2023-11-17 04:51 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +        //Тест проверяет, что будет если считать пустой jsonFile
Для этого есть @DisplayName аннотация на тест

2023-11-17 04:51 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +        reader = new ReadDataFromFile();
а зачем так делаешь? Почему не просто выше сразу 
private static Readable reader = new ReadDataFromFile();
?

2023-11-17 04:52 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +        Assertions.assertFalse(datas.isEmpty());
когда говорю полностью проверить - это значит каждое поле проверить

2023-11-17 04:54 UTC, progressicu commented on Storage/src/test/java/org/example/RequestServiceTest.java
> +            objectMap = readable.readData(getPath());
Уже писал. Зачем ты считываешь из файла, если можно просто руками создать необходимые 1-2 записи в Map и вызвать addAllUsefulObject?

2023-11-17 04:57 UTC, progressicu commented on Storage/src/test/java/org/example/RequestServiceTest.java
> +        requestService.addUsefulObject(objExpected);
зачем ты добавляешь? ты в начале класса уже наполнил requestService какими-то объектами. Так их и запрашивай в таком случае

2023-11-17 04:58 UTC, progressicu commented on Storage/src/test/java/org/example/ReadDataFromFileTest.java
> +public class ReadDataFromFileTest
Где тесты, что будет если кривой файл будет и ещё один, что несуществующий файл

2023-11-27 11:17 UTC, progressicu approved these changes

2023-11-30 13:20 UTC, merged